### ISSUE TITLE
[Enhancement] Iframe to "fake" Responsive

### ISSUE THREAD

**Issue by xtiggerk** [dimanech/atlas-guide#14]
Hey,

I've been using your styleguide for my new project, and i just found a very nice and useful feature into this one:
http://hugeinc.github.io/styleguide/demo/index.html#!introduction 
Offering the possibility to turn the "playground" into desktop / tablet / mobile mode by only applying a class to an existing iframe.
I think this could be a very nice improvement to make!
What do you think?

I love your styleguide tho'! thanks 👍

**Comment by dimanech** [comment]
Thanks for you interest!

This useful thing, but it required different structure of navigation and generation of the page. 
It was already investigated in https://github.com/dimanech/atlas-guide/tree/feature/iframe-structure 
In this branch as approach for the same thing we use dragging of aside, but buttons could be also added. Ex:

<img width="1377" alt="screen shot 2018-06-08 at 10 19 02" src="https://user-images.githubusercontent.com/1180050/41144395-7907a1ec-6b05-11e8-9dd8-50b5662e3018.png">

Iframe structure not play well with static, self-contained, documentation approach that Atlas v1 intend to be. Probably in version 2 Atlas could be much like app that works with his own server, in this case I could do required routing and other different stuff.

**Comment by xtiggerk** [comment]
Thanks for you concern! can't wait v2 then ;)
