### ISSUE TITLE
Stylesheets not loading

### ISSUE THREAD

**Issue by mahaveer0496** [dimanech/atlas-guide#15]
this is what ive been trying 
```
/*md

# Text

Text Colors

Component:
(add ticks to make it work )
``html_example
<p class="text">Some text</p>
``

*/

.text {
  font-size: 20px;
  color: red;
  &--subject {
    color: red;
    font-size: 16px;
    margin-top: 5px;
  }
}
```

this is the config file
```
{  
  "guideSrc": "./src/",
  "guideDest": "./src/guide/",
  "cssSrc": "./src/"
}
```

This is the folder structure 
```
src
....stylesheets/SCSS_files
....index.css
```

This is the output im getting
![image](https://user-images.githubusercontent.com/23198481/41052130-9c62f2ee-69d5-11e8-8d7b-141e4f12fe57.png)

No matter what i do my `.text  .text--subject` classes wont show up in browser

**Comment by mahaveer0496** [comment]
I did more inspection and my CSS does show up in `insights.html` but not in Component page

**Comment by dimanech** [comment]
Hi there,
Atlas not pick up stylesheets automatically, the `cssSrc` used to generate statistic reports.

All you need is overload one template and add styles links manually:

```
{  
  "guideSrc": "./src/",
  "guideDest": "./src/guide/",
  "cssSrc": "./src/",
   "partials": {
       "assetshead": "./src/any/path/to/project-head.mustache", 
    }
}
```

in `project-head.mustache` you will have:

```
<link rel="stylesheet" type="text/css" href="../relative/from/guide/html/path/to/css/index.css" />
```

In this file you could place CSS in any order, that much or not much you project, any additional css that you need, or special CSS for guide etc. etc.

Please see https://github.com/dimanech/atlas-guide#templates-overwrites for more details.

I understand your trouble and I will update "quick starter" in README to make that thing cleaner.

**Comment by mahaveer0496** [comment]
@dimanech I'm not using `mustache` but `react` is it not possible to just add comments in `scss` files and get styleguide generated ?

**Comment by dimanech** [comment]
It is not necessary that your project uses mustache. Mustache is just template engine that used in Atlas. To load your styles into styleguide you, obviously, need links to generated CSS. Please digg down into documentation and development setup in this repo to get the idea how you could integrate this tool into you particular setup and needs.

**Comment by mahaveer0496** [comment]
Okay thanks :)
I tried with Mustache and it worked.
