### ISSUE TITLE
Reference cssstats dependency from npm registry

### ISSUE THREAD

**Issue by wishrd** [dimanech/atlas-guide#17]
Hi,

we are trying to use your atlas-guide but we can't connect to github from our life cycle, we can connect only to an internal repository linked to public npm registry (business environment).

https://github.com/dimanech/atlas-guide/blob/master/package.json#L24

There is any problem to change this line to `"cssstats": "^3.2.0"`?

Thank you!

**Comment by dimanech** [comment]
Hi,
This won't work since used fork has some changes that probably useful only for this project. 

I believe that most simpliest solution is to publish this fork as scoped package. Ex: `@dimanech/cssstat-core`. I could do this. 

Is this works for you?

**Comment by wishrd** [comment]
Oh, sorry, i didn't see that your cssstat was a fork.

Yes, your solution should work.

Thanks!

**Comment by dimanech** [comment]
It is fixed in last minor release (`1.1.4`). You could update to this version to get namespaced dependency by default.

I am going to close this ticket. Please feel free to reopen it in case of any. Thanks!
