### ISSUE TITLE
style encapsulation

### ISSUE THREAD

**Issue by bw1984** [dimanech/atlas-guide#18]
when including a reference to the generated site css file within the "partials" option (as per the docs) the styles also get applied to the styleguide itself, rather than just the individual components examples. 

Is there any way to encapsulate the examples within the guide? I see some options have been explored such as loading the live html_examples blocks within iframes, which would allow this to work. But short of doing a rewrite to handle this, do you have any suggestions on how to keep the imported site/project styles from polluting the styleguide?

**Comment by dimanech** [comment]
Hi there,
With current implementation you couldn't. The presence of project styles and guide styles (or complete another styles instead) in the same scope is how it designed. With this concept in mind on Atlas side we have several things for encapsulation:

* namespace (`atlas-`)
* native cascade stopping properties in form of `all: initial | unset;`
* properties overwrite

It seems like comprehensive set, but obviously it still fragile, like all embedded CSS.

As the quick solution you could create an additional style sheet for your Atlas and fix/overload all things that you faced, without touching your project style sheets. In this case you only need additional CSS import alongside with you project styles imports.

If you find that you fixes could be useful for others you could contribute to Atlas and add them to the streamline. I would be really appreciate this.

As for iframes for code-examples, it is required major changes (as minimum -- separate HTML file for each example). That is far away from simple static "site" generator that Atlas v1 try to be. If you have some ideas about how it could be organized simpler and with "static" in mind, it would be grate contribution.
