### ISSUE TITLE
Statistics based not on sass variables but on css custom properties (as an option)

### ISSUE THREAD

**Issue by dapertutto** [dimanech/atlas-guide#52]
As [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) got its coverage in most evergreen browsers (and could be easily polyfilled in older ones), many devs have started to shift to the new paradigm (instead of sass variables). So do I. Now my projects have less sass variables and more css custom properties. But atlas generate all stats based on sass variables. And if I still can mimic basic declaration for styleguide, f.e.:
```sass
$color-default: #000;

:root {
	--color-default: #{$color-default};
}
```

It is inconvenient and redundant at least. At most this trick wouldn't help much with unsatisfying coverage issues, such as:
```
color
1 issue
1 var(--color-default)
```

It would be great if you can add an option for analyze engine to be able to run through sass variables or css custom properties.

**Comment by dimanech** [comment]
Hi there, 
This is nice idea! Think atlas should work both with sass variables and css custom properties. I will look what we could do with this.

**Comment by dimanech** [comment]
Hi @dapertutto ,
This feature is already on staging phase. Could you please check if it works for your project as expected? To do this, please:

1. Clone `atlas-guide` on `feature/css-cust-props` branch.

```
git clone --single-branch -b feature/css-cust-props --depth 1 git@github.com:dimanech/atlas-guide.git
```

2. Use cloned atlas directory as project dependency. To do this put in `package.json`

```
{
  "dependencies": {
    "atlas-guide": "file:../atlas-guide/"
  }
}
```
and run `npm install`

Right now both CSS custom properties and SCSS variables could be used for project configuration.

**Comment by dapertutto** [comment]
Everything seems to be fine with custom properties on Styleguide and Component description pages. But I've noticed misinterpretation on Insights page. For example if local values for colors are set like this:
```
:root {
	--default-link-c: #ff0;
	--default-placeholder-c: #94a4b2;
}
```
then instead of two unique colors: #ff0 and #94a4b2 I see four: #ff0, #94a4b2, var(--default-link-c), var(--default-placeholder-c). So `var(...)` declarations are left as is (not compiled to final values). This issue, of course, concerns all `var(...)` declaration not only for color attribute.

**Comment by dimanech** [comment]
Thanks, for pointed out. This is good case! CSS custom properties could not be compiled because they are "run time" properties (so as "inherit" keyword). Even if we try to get value from CSSOM it could not be precises because they are depends on applied page sources cascade, structure of that page and runtime page manipulation. So it seems unreal too get this statistic properly. The only thing that I could do is to sort this values separate from colors.

**Comment by dapertutto** [comment]
You are right, no precise statistics could be generated out of custom properties.
I must clarify: I completely forgot that in my final css all declarations containing custom properties are accompanied with preceding 'computed' value (for older browsers sake).
```
.selector {
	color: #94a4b2;
	color: var(--default-placeholder-c);
}
```
So that is why I still see normal representation of colors (and other attributes) on Insights page.

BTW, this 'computed' value come from postcss plugin [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables), so it do the hard lifting to determine the right value for custom property (dunno how accurate in complex cases, but I believe this plugin is the best one among the others).

**Comment by dimanech** [comment]
Yes, it is great plugin, but anyway they need to deal with conventions. 

As about values duplication I am still have no idea how to exclude duplicates. So I am about to push this branch to the release and close this ticket. Please fill free to reopen this ticket or create new in case of any. @dapertutto Thanks!)
